[package]
name = "infinite-auction"
version = "0.2.0"
authors = ["wizzwizz4"]
edition = "2018"
publish = false  # It's not stable yet!

[dependencies.project-brilliant-utilities]
version = "0.2"
path = "../project-brilliant-utilities"
